<a href="https://colab.research.google.com/github/TarunjitYumnam/BitcoinSentimentAnalysisML/blob/main/tensorflow_pytorch_AI_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Constant Data Structure is use for tf

In [2]:
array1 = tf.constant([2,4,6])
array2 = tf.constant([1,3,5])
sum = tf.add(array1,array2)
print(f"{sum} is the result of Addition of two array: ")

[ 3  7 11] is the result of Addition of two array: 


In [3]:
sub = tf.subtract(array1,array2)
print(f"{sub} is the result of Subtraction")

[1 1 1] is the result of Subtraction


In [4]:
mul = tf.multiply(array1,array2)
print(f"{mul} is the result of Multiplication")

[ 2 12 30] is the result of Multiplication


In [5]:
matrix1 = tf.constant([[2,3],[3,5]])
matrix2 = tf.constant([[2,3],[3,4]])
matrix_mul= tf.matmul(matrix1,matrix2)
print(f"{matrix_mul} is the result of Multiplication")

[[13 18]
 [21 29]] is the result of Multiplication


In [6]:
import torch

# Tensor Data Structure is use for torch

In [7]:
array1 = torch.tensor([1,3,5])
array2 = torch.tensor([2,4,6])
result = torch.add(array1,array2)
print(f"{result} is addition result")

tensor([ 3,  7, 11]) is addition result


In [8]:
array1 = torch.tensor([1,3,5])
array2 = torch.tensor([2,4,6])
result = torch.sub(array1,array2)
print(f"{result} is addition result")

tensor([-1, -1, -1]) is addition result


In [9]:
array1 = torch.tensor([1,3,5])
array2 = torch.tensor([2,4,6])
result = torch.mul(array1,array2)
print(f"{result} is addition result")

tensor([ 2, 12, 30]) is addition result


In [10]:
m1 = torch.tensor([[1,3],[2,4]])
m2 = torch.tensor([[2,4],[1,4]])
result = torch.matmul(m1,m2)
print(f"{result} is addition result")

tensor([[ 5, 16],
        [ 8, 24]]) is addition result
